def mostraLinha():
    print('-' * 30)
mostraLinha()
print('     SISTEMA DE ALUNOS       ')
mostraLinha()
mostraLinha()
print('     CADASTRO DE FUNCIONÁRIOS        ')
mostraLinha()
mostraLinha()
print('     ERRO DO SISTEMA     ')
mostraLinha()